// Native-assets build hook: imports the procedural body GLB
// (assets_src/muscle.glb, generated by tool/export_muscle_glb.dart) into a
// flutter_scene scene asset so it can be loaded at runtime with
// `loadScene('assets_src/muscle.glb')`.
//
// Requires `flutter config --enable-native-assets` and
// `--enable-dart-data-assets`, and the Flutter master channel (flutter_scene
// depends on preview Flutter GPU / Native Assets features).
import 'package:hooks/hooks.dart';
import 'package:flutter_scene/build_hooks.dart';

void main(List<String> args) {
  build(args, (config, output) async {
    buildScenes(
      buildInput: config,
      buildOutput: output,
      inputFilePaths: const ['assets_src/muscle.glb'],
      assetMode: SceneAssetMode.dataAssetsIfAvailable,
    );
  });
}
