// GENERATED by tool/export_muscle_glb.dart — do not edit.
//
// The muscle groups owning each glTF material of muscle.glb,
// in material-index order (index 0 is skin → empty list).
const List<List<String>> kMuscleMaterialGroups = [
  [], // 0: Skin
  ['Traps'], // 1
  ['Chest'], // 2
  ['Upper Back'], // 3
  ['Lats'], // 4
  ['Abdominals'], // 5
  ['Lower Back'], // 6
  ['Neck'], // 7
  ['Shoulders'], // 8
  ['Triceps'], // 9
  ['Biceps'], // 10
  ['Forearms'], // 11
  ['Glutes'], // 12
  ['Quadriceps', 'Adductors'], // 13
  ['Hamstrings'], // 14
  ['Calves'], // 15
];
